# Generated by Django 5.0.6 on 2024-06-05 12:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_alter_message_id"),
        ("myapp", "0002_rename_room_message_room_id_alter_message_id"),
    ]

    operations = []
