# Generated by Django 5.0.6 on 2024-06-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_merge_20240605_1750"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adminandagent",
            name="is_active",
        ),
        migrations.AddField(
            model_name="adminandagent",
            name="status",
            field=models.CharField(default="inactive", max_length=10),
        ),
        migrations.AlterField(
            model_name="message",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
